Update integration-test.yaml

diff --git a/.github/workflows/integration-test.yaml b/.github/workflows/integration-test.yaml
--- a/.github/workflows/integration-test.yaml
+++ b/.github/workflows/integration-test.yaml
@@ -151,7 +151,13 @@ jobs:
          npx playwright install-deps
          npm install dotenv --save
          URI="$URI" TOKEN="$TOKEN" URI2="$URI2" TOKEN2="$TOKEN2" ADDITIONAL_PARAMETERS="$ADDITIONAL_PARAMETERS" TOGETHER_TOKEN="$TOGETHER_TOKEN" OPENAI_TOKEN="$OPENAI_TOKEN" AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" GOOGLE_TOKEN="$GOOGLE_TOKEN" DEBUG=pw:api npx playwright test tests/red_teaming.spec.ts
-         
+    
+    - name: Monitor Logs
+      if: always()   # Ensure this runs even if the previous step fails
+      run: |
+        echo "Checking final logs"
+        cat moonshot.log || echo "No logs found"
+        
     - name: Upload Playwright Traces
       if: always()
       uses: actions/upload-artifact@v4
